version: "3.9"
services:
    facetoface-bridge:
        container_name: ${CONTAINER_NAME}
        image: ${CONTAINER_NAME}
        restart: unless-stopped
        tty: true
        env_file: ../../.env
        networks:
            - facetoface-dev-network
